[package]
name = "ping-pong"
version = "0.1.0"
edition = "2021"

default-run = "server"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
